export const SESSION_CUSTOM_TYPE = {
  agentContext: 'agent/context',
  approvalRequested: 'approval/requested',
  approvalResolved: 'approval/resolved',
  contextUsageSnapshot: 'context_usage_snapshot',
  llmRequestCompleted: 'llm/request-completed',
  llmRequestStarted: 'llm/request-started',
  llmRequestHeader: 'llm/request-header',
  runStarted: 'run/started',
  runCompleted: 'run/completed',
  turnStarted: 'turn/started',
  turnCompleted: 'turn/completed',
  runPolicy: 'run/policy',
  sessionArchiveChanged: 'session/archive-changed',
  todoUpdated: 'todo/updated',
  toolExecutionCompleted: 'tool/execution-completed',
  toolExecutionStarted: 'tool/execution-started',
  userInput: 'user/input',
} as const
